name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build and Test using Golang ${{ matrix.go-version }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.18.x, 1.19.x, stable]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: go/src/github.com/refraction-networking/ed25519

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: |
          cd $GITHUB_WORKSPACE/go/src/github.com/refraction-networking/ed25519
          export GOPATH="$GITHUB_WORKSPACE/go"
          go test -v -race ./...

      - name: Ensure proxy builds
        run: |
          cd $GITHUB_WORKSPACE/go/src/github.com/refraction-networking/ed25519
          go build -v -race .

  golangci-lint:
    name: Format and Lint with golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -v --disable structcheck,govet
